[workspace]
resolver = "2"
members = [
  "sdk",
  "sources/baozimh",
  "sources/mangadex",
  "sources/mangabz",
  "sources/manhuagui",
  "sources/manhuaren",
  "sources/noyacg",
  "sources/zaimanhua",
  "sources/happymh",
  "sources/komiic",
  "sources/terrahistoricus",
  "sources/zerobyw",
  "sources/dm5",
  "sources/dongmanmanhua",
  "sources/manhuashe",
  "sources/manhuawu",
  "sources/iqiyi",
  "tools/koma-source-dev",
]
